apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amt-richard-bouaro/automation-helm.git
    path: root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: automation-assessment
  syncPolicy:
    automated:
      selfHeal: true