apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: usermgmt-policy
  namespace: {{ .Values.namespace | default "automation-assessment" }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "usermgmt.name" . }}

  action: ALLOW

  # Temporary allow-all rule (debug / prove-it)
  rules:
    - {}
