apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database }}
  MYSQL_USER: {{ .Values.mysql.auth.username }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password }}