apiVersion: v2
name: automation-assessment
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
 - name: mysql
   version: 14.0.3
   repository: https://charts.bitnami.com/bitnami
   condition: mysql.enabled
